server:
  port:
    8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    username: frxy
    url : jdbc:mysql://localhost:3306/moavies
    password: munib123
  jpa:
    hibernate:
      ddl-auto: update

